#!/usr/bin/env python3
from pathlib import Path
import os


project_root = Path(__file__).resolve().parents[2]
final_out = Path(os.environ.get("WEBRTC_FINAL_OUT", project_root / "out")).resolve()
cmake_dir = final_out / "cmake"
cmake_dir.mkdir(parents=True, exist_ok=True)


def target(name, os_name, cpu, version, lib, runtime="", stl="", config="release"):
    return {
        "name": name,
        "os": os_name,
        "cpu": cpu,
        "version": version,
        "lib": lib,
        "runtime": runtime,
        "stl": stl,
        "config": config,
    }


targets = []
for config in ("release", "debug"):
    name_suffix = "_debug" if config == "debug" else ""
    debug_dir = "/debug" if config == "debug" else ""
    for runtime in ("md", "mt"):
        targets.extend([
            target(f"win7_x86_m109_{runtime}{name_suffix}", "win7", "x86", "m109", f"lib/win7/x86/m109/{runtime}{debug_dir}/webrtc.lib", runtime, config=config),
            target(f"win7_x64_m109_{runtime}{name_suffix}", "win7", "x64", "m109", f"lib/win7/x64/m109/{runtime}{debug_dir}/webrtc.lib", runtime, config=config),
            target(f"win10_x64_m144_{runtime}{name_suffix}", "win10", "x64", "m144", f"lib/win10/x64/m144/{runtime}{debug_dir}/webrtc.lib", runtime, config=config),
            target(f"win10_arm64_m144_{runtime}{name_suffix}", "win10", "arm64", "m144", f"lib/win10/arm64/m144/{runtime}{debug_dir}/webrtc.lib", runtime, config=config),
        ])
    for stl in ("gnu", "libcxx"):
        targets.extend([
            target(f"linux_x64_m144_{stl}{name_suffix}", "linux", "x64", "m144", f"lib/linux/x64/m144/{stl}{debug_dir}/libwebrtc.a", stl=stl, config=config),
            target(f"linux_armhf_m144_{stl}{name_suffix}", "linux", "armhf", "m144", f"lib/linux/armhf/m144/{stl}{debug_dir}/libwebrtc.a", stl=stl, config=config),
            target(f"linux_arm64_m144_{stl}{name_suffix}", "linux", "arm64", "m144", f"lib/linux/arm64/m144/{stl}{debug_dir}/libwebrtc.a", stl=stl, config=config),
        ])
    targets.append(target(f"linux_centos7_x64_m144_libcxx{name_suffix}", "linux-centos7", "x64", "m144", f"lib/linux-centos7/x64/m144/libcxx{debug_dir}/libwebrtc.a", stl="libcxx", config=config))
    for abi in ("armeabi-v7a", "arm64-v8a", "x86", "x86_64"):
        targets.append(target(f"android_{abi.replace('-', '_')}_m144{name_suffix}", "android", abi, "m144", f"lib/android/{abi}/m144{debug_dir}/libwebrtc.a", config=config))
    for os_name, cpu, base, lib_dir in (
        ("macos", "x64", "macos_x64_m144", "lib/macos/x64/m144"),
        ("macos", "arm64", "macos_arm64_m144", "lib/macos/arm64/m144"),
        ("ios", "arm64", "ios_arm64_m144", "lib/ios/arm64/m144"),
        ("ios-simulator", "x64", "ios_simulator_x64_m144", "lib/ios-simulator/x64/m144"),
        ("ios-simulator", "arm64", "ios_simulator_arm64_m144", "lib/ios-simulator/arm64/m144"),
    ):
        targets.append(target(f"{base}{name_suffix}", os_name, cpu, "m144", f"{lib_dir}{debug_dir}/libwebrtc.a", config=config))


def metadata_dir(item):
    debug_dir = "/debug" if item["config"] == "debug" else ""
    if item["os"] in ("win7", "win10"):
        return f'meta/{item["os"]}/{item["cpu"]}/{item["version"]}/{item["runtime"]}{debug_dir}'
    if item["os"].startswith("linux"):
        return f'meta/{item["os"]}/{item["cpu"]}/{item["version"]}/{item["stl"]}{debug_dir}'
    return f'meta/{item["os"]}/{item["cpu"]}/{item["version"]}{debug_dir}'

include_suffixes = [
    "",
    "third_party/abseil-cpp",
    "third_party/boringssl/src/include",
    "third_party/googletest/src/googlemock/include",
    "third_party/googletest/src/googletest/include",
    "third_party/jsoncpp/source/include",
    "third_party/libgav1/src",
    "third_party/libsrtp/config",
    "third_party/libsrtp/crypto/include",
    "third_party/libsrtp/include",
    "third_party/libvpx/source/libvpx",
    "third_party/libyuv/include",
    "third_party/opus/src/include",
    "third_party/perfetto/include",
    "third_party/protobuf/src",
    "third_party/tflite/src",
]


def include_dirs(version):
    result = []
    base = final_out / "include" / version
    for suffix in include_suffixes:
        path = base / suffix if suffix else base
        if path.is_dir():
            result.append(f"${{_libwebrtc_root}}/include/{version}" + (f"/{suffix}" if suffix else ""))
    return result


lines = [
    "# Generated by script/common/generate_cmake_package.py",
    'get_filename_component(_libwebrtc_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)',
    "",
    "function(_libwebrtc_add_imported_target target_name relative_library include_version)",
    '  if(TARGET "${target_name}")',
    "    return()",
    "  endif()",
    '  add_library("${target_name}" STATIC IMPORTED GLOBAL)',
    '  set_target_properties("${target_name}" PROPERTIES',
    '    IMPORTED_LOCATION "${_libwebrtc_root}/${relative_library}"',
    "    INTERFACE_COMPILE_FEATURES cxx_std_17",
    '    INTERFACE_INCLUDE_DIRECTORIES "${ARGN}")',
    "endfunction()",
    "",
    "function(_libwebrtc_append_compile_definitions target_name)",
    '  set_property(TARGET "${target_name}" APPEND PROPERTY INTERFACE_COMPILE_DEFINITIONS ${ARGN})',
    "endfunction()",
    "",
    "function(_libwebrtc_append_link_libraries target_name)",
    '  set_property(TARGET "${target_name}" APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${ARGN})',
    "endfunction()",
    "",
]

for version in ("m109", "m144"):
    lines.append(f"set(_libwebrtc_{version}_includes")
    lines.extend(f'  "{d}"' for d in include_dirs(version))
    lines.extend([")", ""])

for item in targets:
    if not (final_out / item["lib"]).is_file():
        continue
    cmake_name = f"libwebrtc::{item['name']}"
    metadata = metadata_dir(item)
    for notice in ("LICENSE.md", "WebRTC-LICENSE.txt", "WebRTC-PATENTS.txt"):
        if not (final_out / metadata / notice).is_file():
            raise RuntimeError(f"Missing legal notice for {item['name']}: {metadata}/{notice}")
    lines.append(f'_libwebrtc_add_imported_target({cmake_name} "{item["lib"]}" {item["version"]} ${{_libwebrtc_{item["version"]}_includes}})')
    lines.append(f'set_target_properties({cmake_name} PROPERTIES INTERFACE_LIBWEBRTC_BUILD_CONFIG "{item["config"]}")')
    lines.append(f'set_target_properties({cmake_name} PROPERTIES INTERFACE_LIBWEBRTC_LICENSE_FILE "${{_libwebrtc_root}}/{metadata}/LICENSE.md")')
    lines.append(f'set_target_properties({cmake_name} PROPERTIES INTERFACE_LIBWEBRTC_PROJECT_LICENSE_FILE "${{_libwebrtc_root}}/{metadata}/WebRTC-LICENSE.txt")')
    lines.append(f'set_target_properties({cmake_name} PROPERTIES INTERFACE_LIBWEBRTC_PATENTS_FILE "${{_libwebrtc_root}}/{metadata}/WebRTC-PATENTS.txt")')
    if item["os"] in ("win7", "win10"):
        lines.append(f"_libwebrtc_append_compile_definitions({cmake_name} WEBRTC_WIN NOMINMAX WIN32_LEAN_AND_MEAN)")
        lines.append(f'set_target_properties({cmake_name} PROPERTIES INTERFACE_LIBWEBRTC_MSVC_RUNTIME "{item["runtime"]}")')
        win_libs = "ws2_32 secur32 crypt32 iphlpapi winmm dmoguids wmcodecdspuuid msdmo strmiids dxgi d3d11 d2d1 dxguid dwmapi shcore user32 gdi32 advapi32 shell32 ole32 oleaut32 version propsys setupapi"
        if item["os"] == "win10":
            win_libs += " runtimeobject windowsapp"
        lines.append(f"_libwebrtc_append_link_libraries({cmake_name} {win_libs})")
    elif item["os"].startswith("linux"):
        lines.append(f"_libwebrtc_append_compile_definitions({cmake_name} WEBRTC_POSIX WEBRTC_LINUX)")
        lines.append(f'set_target_properties({cmake_name} PROPERTIES INTERFACE_LIBWEBRTC_LINUX_STL "{item["stl"]}")')
        if item["os"] == "linux-centos7":
            lines.append(f'set_target_properties({cmake_name} PROPERTIES INTERFACE_LIBWEBRTC_LINUX_COMPAT "centos7")')
        lines.append(f"_libwebrtc_append_link_libraries({cmake_name} Threads::Threads dl rt X11 Xext Xdamage Xfixes Xcomposite Xrandr Xtst)")
    elif item["os"] == "android":
        lines.append(f"_libwebrtc_append_compile_definitions({cmake_name} WEBRTC_POSIX WEBRTC_ANDROID)")
        lines.append(f"_libwebrtc_append_link_libraries({cmake_name} log android OpenSLES)")
    elif item["os"] == "macos":
        lines.append(f"_libwebrtc_append_compile_definitions({cmake_name} WEBRTC_POSIX WEBRTC_MAC)")
        lines.append(f'_libwebrtc_append_link_libraries({cmake_name} "-framework Foundation" "-framework CoreFoundation" "-framework CoreAudio" "-framework AudioToolbox" "-framework CoreGraphics" "-framework CoreVideo" "-framework IOSurface" "-framework AppKit" "-framework ScreenCaptureKit" "-framework VideoToolbox")')
    elif item["os"].startswith("ios"):
        lines.append(f"_libwebrtc_append_compile_definitions({cmake_name} WEBRTC_POSIX WEBRTC_IOS)")
        lines.append(f'_libwebrtc_append_link_libraries({cmake_name} "-framework Foundation" "-framework AVFoundation" "-framework AudioToolbox" "-framework CoreVideo" "-framework VideoToolbox")')
    lines.append("")

lines.extend([
    "function(_libwebrtc_alias_default concrete_target)",
    '  if(TARGET "${concrete_target}" AND NOT TARGET libwebrtc::webrtc)',
    "    add_library(libwebrtc::webrtc INTERFACE IMPORTED GLOBAL)",
    '    set_target_properties(libwebrtc::webrtc PROPERTIES INTERFACE_LINK_LIBRARIES "${concrete_target}")',
    "  endif()",
    "endfunction()",
    "",
    "function(_libwebrtc_selected_build_config out_suffix)",
    "  if(DEFINED LIBWEBRTC_BUILD_CONFIG)",
    '    string(TOLOWER "${LIBWEBRTC_BUILD_CONFIG}" _config)',
    '  elseif(MSVC AND DEFINED CMAKE_BUILD_TYPE AND CMAKE_BUILD_TYPE STREQUAL "Debug")',
    "    set(_use_debug_crt TRUE)",
    "    if(DEFINED CMAKE_MSVC_RUNTIME_LIBRARY AND NOT CMAKE_MSVC_RUNTIME_LIBRARY STREQUAL \"\")",
    '      if(CMAKE_MSVC_RUNTIME_LIBRARY MATCHES "Debug")',
    "        set(_use_debug_crt TRUE)",
    "      else()",
    "        set(_use_debug_crt FALSE)",
    "      endif()",
    '    elseif(DEFINED CMAKE_CXX_FLAGS_DEBUG AND CMAKE_CXX_FLAGS_DEBUG MATCHES "(^| )/M[TD]($| )")',
    "      set(_use_debug_crt FALSE)",
    "    endif()",
    "    if(_use_debug_crt)",
    "      set(_config debug)",
    "    else()",
    "      set(_config release)",
    "    endif()",
    '  elseif(DEFINED CMAKE_BUILD_TYPE AND CMAKE_BUILD_TYPE STREQUAL "Debug")',
    "    set(_config debug)",
    "  else()",
    "    set(_config release)",
    "  endif()",
    '  if(_config STREQUAL "debug")',
    "    set(_suffix _debug)",
    "  else()",
    '    set(_suffix "")',
    "  endif()",
    '  set("${out_suffix}" "${_suffix}" PARENT_SCOPE)',
    "endfunction()",
    "",
    "function(_libwebrtc_selected_msvc_runtime out_var)",
    "  if(DEFINED LIBWEBRTC_MSVC_RUNTIME)",
    '    string(TOLOWER "${LIBWEBRTC_MSVC_RUNTIME}" _runtime)',
    '  elseif(DEFINED CMAKE_MSVC_RUNTIME_LIBRARY AND CMAKE_MSVC_RUNTIME_LIBRARY MATCHES "DLL")',
    "    set(_runtime md)",
    '  elseif(DEFINED CMAKE_MSVC_RUNTIME_LIBRARY AND CMAKE_MSVC_RUNTIME_LIBRARY MATCHES "MultiThreaded")',
    "    set(_runtime mt)",
    "  else()",
    "    set(_runtime md)",
    "  endif()",
    '  set("${out_var}" "${_runtime}" PARENT_SCOPE)',
    "endfunction()",
    "",
    "function(_libwebrtc_selected_linux_stl out_var)",
    "  if(DEFINED LIBWEBRTC_LINUX_STL)",
    '    string(TOLOWER "${LIBWEBRTC_LINUX_STL}" _stl)',
    "  else()",
    "    set(_stl gnu)",
    "  endif()",
    '  set("${out_var}" "${_stl}" PARENT_SCOPE)',
    "endfunction()",
    "",
    "function(_libwebrtc_selected_linux_compat out_var)",
    "  if(DEFINED LIBWEBRTC_LINUX_COMPAT)",
    '    string(TOLOWER "${LIBWEBRTC_LINUX_COMPAT}" _compat)',
    "  else()",
    "    set(_compat ubuntu18)",
    "  endif()",
    '  set("${out_var}" "${_compat}" PARENT_SCOPE)',
    "endfunction()",
    "",
    "_libwebrtc_selected_build_config(_libwebrtc_config_suffix)",
    "if(WIN32)",
    "  _libwebrtc_selected_msvc_runtime(_libwebrtc_msvc_runtime)",
    '  if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|AARCH64|arm64|aarch64")',
    "    _libwebrtc_alias_default(libwebrtc::win10_arm64_m144_${_libwebrtc_msvc_runtime}${_libwebrtc_config_suffix})",
    "  elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)",
    '    if(DEFINED LIBWEBRTC_WINDOWS_FAMILY AND LIBWEBRTC_WINDOWS_FAMILY STREQUAL "win7")',
    "      _libwebrtc_alias_default(libwebrtc::win7_x64_m109_${_libwebrtc_msvc_runtime}${_libwebrtc_config_suffix})",
    "    else()",
    "      _libwebrtc_alias_default(libwebrtc::win10_x64_m144_${_libwebrtc_msvc_runtime}${_libwebrtc_config_suffix})",
    "    endif()",
    "  else()",
    "    _libwebrtc_alias_default(libwebrtc::win7_x86_m109_${_libwebrtc_msvc_runtime}${_libwebrtc_config_suffix})",
    "  endif()",
    "elseif(ANDROID)",
    '  if(ANDROID_ABI STREQUAL "armeabi-v7a")',
    "    _libwebrtc_alias_default(libwebrtc::android_armeabi_v7a_m144${_libwebrtc_config_suffix})",
    '  elseif(ANDROID_ABI STREQUAL "arm64-v8a")',
    "    _libwebrtc_alias_default(libwebrtc::android_arm64_v8a_m144${_libwebrtc_config_suffix})",
    '  elseif(ANDROID_ABI STREQUAL "x86")',
    "    _libwebrtc_alias_default(libwebrtc::android_x86_m144${_libwebrtc_config_suffix})",
    '  elseif(ANDROID_ABI STREQUAL "x86_64")',
    "    _libwebrtc_alias_default(libwebrtc::android_x86_64_m144${_libwebrtc_config_suffix})",
    "  endif()",
    "elseif(APPLE)",
    "  if(IOS)",
    "    _libwebrtc_alias_default(libwebrtc::ios_arm64_m144${_libwebrtc_config_suffix})",
    '  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|AARCH64|arm64|aarch64")',
    "    _libwebrtc_alias_default(libwebrtc::macos_arm64_m144${_libwebrtc_config_suffix})",
    "  else()",
    "    _libwebrtc_alias_default(libwebrtc::macos_x64_m144${_libwebrtc_config_suffix})",
    "  endif()",
    "elseif(UNIX)",
    "  _libwebrtc_selected_linux_stl(_libwebrtc_linux_stl)",
    "  _libwebrtc_selected_linux_compat(_libwebrtc_linux_compat)",
    '  if(_libwebrtc_linux_compat STREQUAL "centos7")',
    "    _libwebrtc_alias_default(libwebrtc::linux_centos7_x64_m144_libcxx${_libwebrtc_config_suffix})",
    '  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")',
    "    _libwebrtc_alias_default(libwebrtc::linux_arm64_m144_${_libwebrtc_linux_stl}${_libwebrtc_config_suffix})",
    '  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm")',
    "    _libwebrtc_alias_default(libwebrtc::linux_armhf_m144_${_libwebrtc_linux_stl}${_libwebrtc_config_suffix})",
    "  else()",
    "    _libwebrtc_alias_default(libwebrtc::linux_x64_m144_${_libwebrtc_linux_stl}${_libwebrtc_config_suffix})",
    "  endif()",
    "endif()",
])

(cmake_dir / "LibWebRTCTargets.cmake").write_text("\n".join(lines) + "\n", encoding="utf-8")
(cmake_dir / "LibWebRTCConfig.cmake").write_text(
    """# Generated LibWebRTC CMake package.
include(CMakeFindDependencyMacro)

if(UNIX AND NOT APPLE AND NOT ANDROID)
  find_dependency(Threads)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/LibWebRTCTargets.cmake")

if(NOT TARGET libwebrtc::webrtc)
  set(LibWebRTC_FOUND FALSE)
  set(LibWebRTC_NOT_FOUND_MESSAGE "No libwebrtc target matches the current platform/architecture/runtime/build-config. Use a concrete libwebrtc target or build that package first.")
endif()
""",
    encoding="utf-8",
)
(final_out / "LibWebRTCConfig.cmake").write_text(
    'include("${CMAKE_CURRENT_LIST_DIR}/cmake/LibWebRTCConfig.cmake")\n',
    encoding="utf-8",
)
(cmake_dir / "README.md").write_text(
    """# LibWebRTC CMake package

Set `LIBWEBRTC_BUILD_CONFIG=Debug` before `find_package()` to select Debug
packages. On Windows the automatic default only selects Debug packages when the
current Debug build uses the debug MSVC CRT (`/MDd` or `/MTd`). If a Qt Debug
build uses the release CRT (`/MD`), keep the default Release WebRTC package or
set `LIBWEBRTC_BUILD_CONFIG=Release`. Windows runtime selection still uses
`LIBWEBRTC_MSVC_RUNTIME`; Linux STL selection still uses `LIBWEBRTC_LINUX_STL`. Set
`LIBWEBRTC_LINUX_COMPAT=centos7` to select the CentOS 7-compatible x64 libc++
package when it is present.
""",
    encoding="utf-8",
)
print(f"Generated CMake package under {cmake_dir}")
